
<font size="4">

## Day 1

--- 

**Introduction**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/introduction.html" class="btn btn-warning btn-xs" role="button">Introduction</a>

-   How animal acoustic signals look like?
-   Analytical workflow in bioacoustics research
-   Advantages of programming
-   Course structure

**Basic R concepts**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/r_basics.html" class="btn btn-warning btn-xs" role="button">R basics</a>

-   Object types in R
-   Subsetting
-   Style matters
-   R documentation

**What is sound?**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/sound.html" class="btn btn-warning btn-xs" role="button">Sound</a>

-   Sound as a time series
-   Sound as a digital object
-   Acoustic data in R
-   ‘wave’ object structure
-   ‘wave’ object manipulations
-   additional formats

---

&nbsp; 

## Day 2

---

**Building spectrograms**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/spectrograms.html" class="btn btn-warning btn-xs" role="button">Building
spectrograms</a>

-   Fourier transform
-   Building a spectrogram
-   Characteristics and limitations
-   Spectrograms in R

**Package seewave**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/seewave.html" class="btn btn-warning btn-xs" role="button">seewave</a>

-   Explore, modify and measure ‘wave’ objects
-   Spectrograms and oscillograms
-   Filtering and re-sampling
-   Acoustic measurements

**Annotation software**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/annotations.html" class="btn btn-warning btn-xs" role="button">annotations</a>

-   Raven / audacity
-   Open and explore recordings
-   Modify-optimize visualization parameters
-   Annotate signals

---

&nbsp;

## Day 3

---


**Automatic detection**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/ohun.html" class="btn btn-warning btn-xs" role="button">Automatic detection</a>

-   ohun package for optimize acoustic signal detection
-   Detection using amplitude, frequency, and time filters
    (`ohun::energy_detector()`)
-   Detection using cross-correlation (`ohun::template_detector()`)
-   Frequency range detection (`warbleR::freq_range()` and `warbleR::freq_range_detec()`)

**Intro to warbleR**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/intro_to_warbler.html" class="btn btn-warning btn-xs" role="button">Intro
to warbleR</a>

-   Intro to warbleR
-   Selection tables
-   Extended selection tables
-   Selection table manipulation
-   warbleR functions and the bioacoustics analysis workflow


**Quantifying acoustic signal structure**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/measure_acoustic_structure.html" class="btn btn-warning btn-xs" role="button">Quantify structure</a>

-   Spectro-temporal measurements (`spectro_analysis()`)
-   Parameter description
-   Harmonic content
-   Cepstral coefficients (`mfcc_stats()`)
-   Cross-correlation (`cross_correlation()`)
-   Dynamic time warping (`freq_DTW()`)
-   Signal-to-noise ratio (`sig2noise()`)
-   Inflections (`inflections()`)
-   Parameters at other levels (`song_analysis()`)

---

&nbsp; 

## Day 4

---

**Characterizing hierarchical levels in acoustic signals**

-   Creating ‘song’ spectrograms (`full_spectrograms()`,
    `spectrograms()`)
-   ‘Song’ parameters (`song_analysis()`)

**Choosing the right method for quantifying structure**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/comparing_methods.html" class="btn btn-warning btn-xs" role="button">Comparing methods</a>

-   Compare different methods for quantifying structure
    (`compare_methods()`)

**Quality control in recordings and annotation**
<a href="https://marce10.github.io/BOKU-Analysis-of-animal-acoustic-signals-in-R-2022/quality_checks.html" class="btn btn-warning btn-xs" role="button">Quality checks</a>

-   Check and modify sound file format (`check_wavs()`, `info_wavs()`,
    `duration_wavs()`, `mp32wav()` y `fix_wavs()`)
-   Tuning spectrogram parameters (`tweak_spectro()`)
-   Double-checking selection tables (`check_sels()`, `spectrograms()`,
    `full_spectrograms()` & `catalog()`)
-   Re-adjusting selections (`tailor_sels()`)


---

&nbsp; 

## Day 5

---